theme = "custom"

[custom_theme]
base = "catppuccin-mocha"
label = "Catppuccin Mocha"
background = "#11111b"
panel = "#1e1e2e"
panelAlt = "#352f4d"
border = "#493963"
accent = "#89b4fa"
accentMuted = "#cba6f7"
text = "#cdd6f4"
muted = "#a6adc8"
contextBg = "#181825"
contextContentBg = "#181825"
addedBg = "#20332b"
removedBg = "#37242f"
movedAddedBg = "#3a3425"
movedRemovedBg = "#3a3425"
addedContentBg = "#284033"
removedContentBg = "#442a37"
addedSignColor = "#a6e3a1"
removedSignColor = "#f38ba8"
lineNumberBg = "#11111b"
lineNumberFg = "#b4befe"
selectedHunk = "#493963"
badgeAdded = "#a6e3a1"
badgeRemoved = "#f38ba8"
badgeNeutral = "#a6adc8"
fileNew = "#a6e3a1"
fileDeleted = "#f38ba8"
fileRenamed = "#f9e2af"
fileModified = "#89b4fa"
fileUntracked = "#94e2d5"
noteBorder = "#f5c2e7"
noteBackground = "#1e1e2e"
noteTitleBackground = "#493963"
noteTitleText = "#cdd6f4"
